version: '3.7'

services:
  server:
    build: ./server
    container_name: "server-grpc"
    volumes:
      - ./server:/practice-grpc
    ports:
      - "8080:8080"
    tty: true

  client:
    build: ./client
    container_name: "client-grpc"
    volumes:
      - ./client:/practice-grpc
    tty: true
